default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: postgres
      password:  M519848leq8r+++
      host:     <%= ENV['PG_HOST'] || 'localhost' %> 
      port: 5432 
       #<%= ENV['PASSWORD'] %> 
#<%= ENV['USERNAME'] %> 
development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production: 
  <<: *default
  database: app_production